language: python
python:
  - "2.7"
before_install:
  - "pip install -r requirements.txt"
install:
  - "pip install coveralls"
before_script:
  - export PYTHONPATH=.
  - python app/models.py
  - python main/manage.py db migrate
script:
  - nosetests --with-coverage
after_success:
  - coveralls
branches:
  only:
  - chore-coderefactor
  - develop
  - master
services:
  - sqlite
